### ISSUE TITLE
🛑 Comer al toque is down

### ISSUE THREAD

**Issue by drandredev** [INNARSSAC/innarsupptime#4]
In [`7844c9c`](https://github.com/INNARSSAC/innarsupptime/commit/7844c9c7519f6e4af3be4ba1770565b1e1696bbb
), Comer al toque (https://www.comeraltoque.com/) was **down**:
- HTTP code: 503
- Response time: 15198 ms

**Comment by drandredev** [comment]
Problems with pulls, @DiegoPamo is checking the new files.

**Comment by DiegoPamo** [comment]
Problema resuelto.

**Comment by Raul122-dev** [comment]
Problem solved.

**Comment by drandredev** [comment]
Closing this.
